### PR TITLE
airframe-di: throw exceptions occurred at shutdown hooks later

### LINKED ISSUE #649: airframe-di: Exception safe shutdown hook chain
For now, if some exception happens during an onShutdown hook process, the other subsequent shutdown hooks will not be called. 

To properly close resources, we should handle exceptions at FILOLifeCycleExecutor

### PR DESCRIPTION
**Pull request by xerial**
Resolves #649

### CODE REVIEW

File: airframe-di-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala [hunk 1]
```diff
@@ -46,7 +46,7 @@ private[wvlet] object AirframeMacros {
         if (t.toString.contains("#")) {
           false
         } else {
-          true
+          hasPublicDefaultConstructor
```
Comment (xerial) [inline airframe-di-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala]: We can't instantiate inner classes without any public default constructor
